#!/bin/bash
set -e

# Create link
ln -s /opt/syncbootpart/bin/syncbootpart /usr/bin/syncbootpart 2>/dev/null || true

# Create kernel update script
echo -e '#!/bin/sh\n/opt/syncbootpart/bin/syncbootpart\nexit 0' > /etc/kernel/postinst.d/zzzzzzz-syncbootpart 2>/dev/null || true
chmod +x /etc/kernel/postinst.d/zzzzzzz-syncbootpart 2>/dev/null || true

# Update MAN pages
mandb -q 2>/dev/null || true

# First run
/opt/syncbootpart/bin/syncbootpart || true

# Just loading to suppress warning
. /usr/share/debconf/confmodule || true

# Done
exit 0
