.\" Manpage for SyncBootPart
.\" Contact jmedved@jmedved.com to correct errors or typos.
.TH SYNCBOOTPART 1 "TODAY" "MAJOR.MINOR.PATCH" "syncbootpart man page"

.SH NAME

syncbootpart \- Boot partition synchronizing


.SH SYNOPSIS

.ad l
\fBsyncbootpart\fR


.SH DESCRIPTION
Syncing boot partitions.


.SH EXAMPLES

.TP
\fBsyncbootpart\fR
Syncs /boot and /boot/efi partitions with their mirror.


.SH AUTHOR

Josip Medved <jmedved@jmedved.com>
